### PR TITLE
draft: add newspaper viewer

### PR DESCRIPTION
**Pull request by wykhuh**
@adamjarling @mathewjordan  Here's a demo of a newspaper viewer.
- Highlights the search term on the page using annotations. 
- Show all instances of the search term in the information panel. 
- When users clicks on a search term in the information panel, zoom and pan to the word on the newspaper page. 

https://github.com/samvera-labs/clover-iiif/assets/6968611/5d6f0ecd-2f9b-4db6-bb1d-16f031a65081

 I had to make many modifications to Clover for newspaper demo. Adam mentioned that y'all will be working on adding support for more annotation types and add the ability to search OCR text, which is what I'm doing for the the newspaper viewer. Can we meet and discuss what changes would be implemented in Clover, and what changes would be implemented in a 3rd-part CustomDisplay plugin? We can also discuss how to coordinate our work since both of our teams need better annotation support and the ability to search OCR text.  

Here are the changes I made
- update Clover to handle annotations with various motivations.  Store the annotations that are not `supplementing` as `annotationResources` 
- add `pages/docs/viewer/annotations.mdx` to display the  "Other kinds of annotations" recipes in the IIIF cookbook. Some of the annotations work, some do not.
- Add hardcoded newspaper manifests `public/manifest/newspaper/`
- Use  annotations with motivation `tagging` to display the search terms.
- Add `src/lib/annotation-overlays.ts` to draw overlays for the highlighted search terms.
- Use  [openseadragon svg plugin](https://github.com/openseadragon/svg-overlay/issues/34#issuecomment-1147992921) to display svg overlays. 
- Add `src/components/Viewer/InformationPanel/AnnotationResource.tsx` and `src/components/Viewer/InformationPanel/AnnotationItem.tsx` to display the search terms in the information panel
- store the instance of openseadragon viewer in the `ViewerContext` so that other components can access the openseadragon viewer. 
- use openseadrgon `viewport.fitBounds` in `AnnotationItem` to handle the zoom and pan when user clicks a search term.
- add `annotationOverlays` to `ViewerContext` that lets people set the color, opacity, and zoom level of the annotation overlays.

TODO:
- add the ability for users to search within a particular issue
- add IIIF content search
- fix bugs with svg overlays
- add custom navigation to move between issues and pages
- use annotations to display all the OCR text for a page.

### CODE REVIEW

**Comment by adamjarling** [comment]
@wykhuh Hey thanks for sharing.  I'll take a look this week and get back to you with some thoughts.

**Comment by mathewjordan** [comment]
@wykhuh @adamjarling 

This is really great work and will make Clover even stronger when it supports these type of annotations. @adamjarling and I were chatting over things and noted a few items that we may want to organize before we merge in this PR. Most of these are things where we used simplified/generic language to describe things in the past and now want to make things a little more fundamentally sound before adding additional complexity.

1. We may we want to develop a solution to normalize all of our Annotations and provide leaf components (like the InformationPanel tabs) access to that data. In doing so we could have `supplementing`, `commenting`, `highlighting` (and others) annotations in an array with a standard shape. 

https://github.com/samvera-labs/clover-iiif/blob/e790622d5b4aab24674d83cdd6ec93182d65607d/src/components/Viewer/Viewer/Viewer.tsx#L90-L106

2. The hardcoded label could be set in configuration file elsewhere, either the default ConfigOptions or some other constants file. The shape of this label should also be: 

https://github.com/samvera-labs/clover-iiif/blob/e790622d5b4aab24674d83cdd6ec93182d65607d/src/hooks/use-iiif/getAnnotationResources.ts#L80

3. We have been working [on a new component](https://github.com/samvera-labs/clover-iiif/pull/136) that also leverages Annotations with textual bodies. We will have some overlapping functionality and components between your work here and my PR noted above. Because of these, we should probably note which components or helpers could be moved to shared directories.

Note, you PR works wonders with my fixture manifest here: https://raw.githubusercontent.com/mathewjordan/iiif/main/manifest/tsg/commenting.json

**Comment by mathewjordan** [comment]
Just noting that this should be item 4.

To integrate these annotations with all types of canvases (Image, Custom, Video, etc...), we may want to abstract this out and dispatch the active annotation to the viewer context. From there, we can handle all openseadragon viewport changes or any custom handlers for custom display.

https://github.com/samvera-labs/clover-iiif/blob/e790622d5b4aab24674d83cdd6ec93182d65607d/src/components/Viewer/InformationPanel/AnnotationItem.tsx#L20-L61

**Comment by adamjarling** [comment]
This work was continued, and eventually PR'd here:  https://github.com/samvera-labs/clover-iiif/pull/170

**Pull request closed without merging**
